# Generated by Django 5.1 on 2024-08-20 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 20, 17, 55, 35, 43860))),
            ],
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
