# Generated by Django 5.1 on 2024-08-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_daily_delete_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
