# Generated by Django 5.1 on 2024-09-04 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0005_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='daily',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='daily.daily'),
            preserve_default=False,
        ),
    ]
